---
#Setup the base config for a PHP Apache Instance
- hosts: localhost
  vars:

  tasks:

    - name: Import remi GPG key.
      rpm_key:
        key: http://rpms.remirepo.net/RPM-GPG-KEY-remi
        validate_certs: false
      become: true
    - name: Install remi Repository for PHP
      yum:
        name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
        state: installed
      become: true
    - name: Enable Yum Repository for remi
      shell: sudo yum-config-manager --enable remi-php71
    - name: Install Required Applications
      yum:
        name: ['git','java-1.8.0-openjdk','httpd-2.4.6','php71','php71-php-common','php71-php-pdo','php71-php-mbstring','php71-php-xml','php71-php-gmp','php71-php-fpm','php71-php-openssl','php71-php-json','php71-php-zip','php71-php-mysql','php71-php','firewalld']
        state: latest
      become: true
    - name: Install PHP Composer 1.6.2
      shell: |
        sudo ln -s /usr/bin/php71 /usr/bin/php
        exit 0
      become: true      
    - name: Install PHP Composer 1.6.2
      shell: |
        cd /tmp
        curl -sS https://getcomposer.org/installer | php
        /usr/bin/mv composer.phar /usr/bin/composer
        exit 0
      become: true
    - name: Start firewalld
      systemd:
        name: firewalld
        state: started
      become: true
    - name: Restart HTTPD
      systemd:
        name: httpd
        state: restarted
      become: true
    - name: Disable SE Linux to permit scripted rule add
      shell: |
        setenforce Permissive
      become: yes
    - name: Set local Firewall Permissions for http
      firewalld:
        service: http
        permanent: true
        state: enabled
      async: 30
      poll: 10
      become: true
    - name: Wait for FW command to complete
      pause:
        seconds: 5
    - name: Enable SE Linux to permit scripted rule add
      shell: |
        setenforce Enforcing
      become: yes
    - name: Start firewalld
      systemd:
        name: firewalld
        state: restarted    
