# Author: A.Bacchus
# Date : 03/30/2021
# Description : This playbook was created to setup the timebank software

---
- hosts: localhost
  vars:
    user: hourworld
    #Run this command to get the password
    #Password is set as hourworld
    #python3 -c 'import crypt,getpass;pw=getpass.getpass();print(crypt.crypt(pw) if (pw==getpass.getpass("Confirm: ")) else exit())'
    password: "$6$C/.LtJfFVoQB6Mgr$voSn4BX7EZnzgE5ncGByyetJuCNEGfHhHaIboouDilTMzr6M2eKrdkrz4yJBTP2Y7atKVKwhRvL1H7I2GgA6W0"
  tasks:

  - name: create user
    user:
      name: "{{ user }}"
      password: "{{ password }}"
    ignore_errors: yes
    become: true

  - name: setenforce
    command: "{{ item }}"
    with_items:
      - setenforce 0
    ignore_errors: yes
    become: true

  - name: Install repos
    command: "dnf install {{ item }} -y"
    with_items:
      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
      - https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    become: true

  - name: Ensure SELinux is set to permissive mode
    lineinfile:
      path: /etc/selinux/config
      regexp: '^SELINUX='
      line: SELINUX=permissive

  - name: Install apache and php packages
    command: "dnf install {{ item }} -y"
    with_items:
      - httpd
      - php56
      - php56-php-mbstring
      - php56-php-mysql
      - php56-php-gd
      - php56-php-apcu
      - php56-php-fpm
    become: true

  - name: Create timebank directories
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - /home/hourworld/TNTv1
      - /home/hourworld/TNTv1/www
      - /home/hourworld/TNTv1/etc
      - /home/hourworld/TNTv1/tmp
      - /home/hourworld/TNTv1/log
      - /home/hourworld/TNTv1/UPeml
    become: true

  - name: Set Listner
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^Listen 80'
      line: Listen 0.0.0.0:80

  - name: Set User
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^User apache'
      line: User hourworld

  - name: Set Docroot
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^DocumentRoot'
      line: DocumentRoot "/home/hourworld/TNTv1/www"

  - name: Set /var/www
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^<Directory "/var/www"'
      line: <Directory "/home/hourworld/TNTv1">

  - name: Set /var/www/html
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^<Directory "/var/www/html"'
      line: <Directory "/home/hourworld/TNTv1/www">

  
  - name: Creating a test html file 1
    copy:
      dest: "/home/hourworld/TNTv1/www/index.html"
      content: |
        <h1> this is a test from the automation </h1>

  
  - name: Enable/Start fpm and apache
    command: "systemctl {{ item }}"
    with_items:
      - enable httpd
      - enable php56-php-fpm
      - restart httpd
      - restart php56-php-fpm
    become: true