# Author: A.Bacchus
# Date : 03/30/2021
# Description : This playbook was created to setup the timebank software

---
- hosts: localhost
  vars:
    user: hourworld
    userpwd: hourworld
    apphome: /var/hourworld
  tasks:

  - name: Ansible get date time
    debug:
     var: ansible_date_time

  - name: generate hash
    command: python3 -c 'import crypt; print (crypt.crypt("This is my Password", "{{ userpwd }}"))'
    become: true
    register: mypass

  - name: Print the generated password hash
    debug:
      msg: "The password hash is  {{ mypass.stdout_lines }}"

  - name: create user
    user:
      name: "{{ user }}"
      password: "{{ mypass.stdout_lines }}"
    ignore_errors: yes
    become: true

  - name: setenforce
    command: "{{ item }}"
    with_items:
      - setenforce 0
    ignore_errors: yes
    become: true

  - name: Install repos
    command: "dnf install {{ item }} -y"
    with_items:
      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
      - https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    become: true

  - name: Ensure SELinux is set to permissive mode
    lineinfile:
      path: /etc/selinux/config
      regexp: '^SELINUX='
      line: SELINUX=permissive
    become: true

  - name: Install apache and php packages
    command: "dnf install {{ item }} -y"
    with_items:
      - httpd
      - php56
      - php56-php-mbstring
      - php56-php-mysql
      - php56-php-gd
      - php56-php-apcu
      - php56-php-fpm
    become: true

  - name: Create timebank directories
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - "{{ apphome }}/TNTv1"
      - "{{ apphome }}/TNTv1/www"
      - "{{ apphome }}/TNTv1/etc"
      - "{{ apphome }}/TNTv1/tmp"
      - "{{ apphome }}/TNTv1/log"
      - "{{ apphome }}/TNTv1/UPeml"
    become: true

  - name: Set Listner
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^Listen 80'
      line: Listen 0.0.0.0:80
    become: true

  - name: Set Docroot
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^DocumentRoot'
      line: DocumentRoot "{{ apphome }}/TNTv1/www"
    become: true

  - name: Set /var/www
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^<Directory "/var/www"'
      line: <Directory "{{ apphome }}/TNTv1">
    become: true

  - name: Set /var/www/html
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^<Directory "/var/www/html"'
      line: <Directory "{{ apphome }}/TNTv1/www">
    become: true

  
  - name: Creating a phpinfo page
    copy:
      dest: "{{ apphome }}/TNTv1/www/index.php"
      content: |
        <h3>This page was generated by the ansible automation "{{ ansible_date_time.iso8601 }}"</h3>
        <?php phpinfo(); ?>
    become: true

  - name: Set permission
    command: "chmod 775 -R {{ apphome }}"
    become: true

  - name: Set local Firewall Permissions for http
    firewalld:
      service: http
      permanent: true
      state: enabled
    async: 30
    poll: 10
    become: true

  - name: Enable/Start fpm and apache
    command: "systemctl {{ item }}"
    with_items:
      - enable httpd
      - enable php56-php-fpm
      - restart httpd
      - restart php56-php-fpm
    become: true
