# Author: A.Bacchus
# Date : 03/30/2021
# Description : This playbook was created to setup the timebank software

---
- hosts: localhost
  vars:
    user: hourworld
    #Run this command to get the password
    #Password is set as hourworld
    #python3 -c 'import crypt,getpass;pw=getpass.getpass();print(crypt.crypt(pw) if (pw==getpass.getpass("Confirm: ")) else exit())'
    password: "$6$C/.LtJfFVoQB6Mgr$voSn4BX7EZnzgE5ncGByyetJuCNEGfHhHaIboouDilTMzr6M2eKrdkrz4yJBTP2Y7atKVKwhRvL1H7I2GgA6W0"
  tasks:

  - name: create user
    user:
      name: "{{ user }}"
      password: "{{ password }}"
    ignore_errors: yes
    become: true

  - name: setenforce
    command: "{{ item }}"
    with_items:
      - setenforce 0
    ignore_errors: yes
    become: true

  - name: Install repos
    command: "dnf install {{ item }} -y"
    with_items:
      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
      - https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    become: true

  - name: Ensure SELinux is set to permissive mode
    lineinfile:
      path: /etc/selinux/config
      regexp: '^SELINUX='
      line: SELINUX=permissive

  - name: Install apache and php packages
    command: "dnf install {{ item }} -y"
    with_items:
      - httpd
      - php56
      - php56-php-mbstring
      - php56-php-mysql
      - php56-php-gd
      - php56-php-apcu
      - php56-php-fpm
    become: true

  - name: Create timebank directories1
    file:
      path: /home/hourworld/TNTv1
      state: directory
      become: yes
      become_user: hourworld

  - name: Create timebank directories
    command: " {{ item }} "
    with_items:
      - cd ~
      - mkdir -p TNTv1 TNTv1/www TNTv1/etc TNTv1/tmp TNTv1/log TNTv1/UPeml
    become: yes
    become_user: hourworld

  
  - name: Enable/Start fpm and apache
    command: "systemctl {{ item }}"
    with_items:
      - enable httpd
      - enable php56-php-fpm
      - start httpd
      - start php56-php-fpm
    become: true