# Author: A.Bacchus
# Date : 02/20/2019
# Description : This playbook is built to provisioned an OSX hardware to a state required for IOS development

---
- hosts: localhost
  vars:

  tasks:
  #Install Pip
  - name: Check if pip is already installed
    stat:
      path: /Library/Python/2.7/site-packages/pip-19.0.3-py2.7.egg
    register: p

  - name: Install Pip
    command: easy_install pip
    when: not p.stat.exists

  #Install Python modules
  - name: Install Python modules
    command: pip install {{ item }}
    with_items:
      - consulate
      - requests
    become: yes


  #Install Java
  - name: Check if java is already installed
    stat:
      path: /Library/Java/JavaVirtualMachines/
    register: j

  - name: Installing Java
    command: "{{ item }}"
    with_items:
      - brew tap AdoptOpenJDK/openjdk
      - brew install adoptopenjdk/openjdk/adoptopenjdk-openjdk8 
    when: not j.stat.exists


  #Install Fastlane
  - name: Check if Fastlane is already installed
    stat:
      path: /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/bin/fastlane
    register: b
  
  - name: Install Fastlane if not already installed
    command: gem install fastlane -NV
    when: not b.stat.exists

