# Author: A.Bacchus
# Date : 02/20/2019
# Description : This playbook is built to provisioned an OSX hardware to a state required for IOS development

---
- hosts: localhost
  vars:

  tasks:
  #Install Pip
  - name: Check if pip is already installed
    stat:
      path: /Library/Python/2.7/site-packages/pip-19.0.3-py2.7.egg
    register: p

  - name: Install Pip
    command: easy_install pip
    when: not p.stat.exists

  #Install Python modules
  - name: Install Python modules
    command: pip install {{ item }}
    with_items:
      - consulate
      - requests
    become: yes

  #Install homebrew
  - name: Check if Homebrew is already installed
    stat:
      path: /usr/local/bin/brew
    register: h
  
  - name: Install Homebrew
    command: ruby /Users/abacchus/Desktop/ansible/homebrew.rb
    when: not h.stat.exists

  #Install Java
  - name: Check if java is already installed
    stat:
      path: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk
    register: j

  - name: Installing Java
    command: "{{ item }}"
    with_items:
      - brew tap AdoptOpenJDK/openjdk
      - brew cask reinstall adoptopenjdk8
    when: not j.stat.exists


  #Install wget
  - name: Check if wget is already installed
    stat:
      path: /usr/local/bin/wget
    register: w

  - name: Installing wget
    command: brew install wget
    when: not w.stat.exists


    #Install bundle
  - name: Check if bundle is already installed
    stat:
      path: /usr/local/bin/bundle
    register: b

  - name: Installing bundle
    command: brew install bundle
    when: not b.stat.exists


  #Install xCode Tools if doesn't exist
  - name: Check if Xcode is already installed
    stat:
      path: /Library/Developer/CommandLineTools
    register: x
  
  - name: Install Xcode dev tools if xcode is installed
    command: xcode-select --install
    when: not x.stat.exists

  #Install Fastlane
  - name: Check if Fastlane is already installed
    stat:
      path: /usr/local/bin/fastlane
    register: b
  
  - name: Install Fastlane if not already installed
    command: gem install fastlane -NV
    when: not b.stat.exists
